openapi: 3.1.1
info:
  title: "API First"
  version: "1.0.0"
  description: "Creando una API FIRST con el curso de platzi"
servers:
  - url: "http://localhost:3000"
    description: "Local server"

components:
  schemas:
    RootResponse:
      type: string

    HelloResponse:
      type: object

paths:
  /: 
    get:
      summary: Welcome
      responses:
        200:
          description: "A succesful response"
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/RootResponse"
  /hello:
    get:
      summary: Hello World
      responses:
        200:
          description: "A succesful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
  /users:
    post:
      summary: Crea un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
               - name
               - age
               - email
              properties:
                name:
                  type: string
                  description: Nombre del usuario
                  minLength: 2
                age:
                  type: integer
                  description: Edad del usuario
                  minimum: 18
                  maximum: 120
                email:
                  type: string
                  description: Correo electrónico del usuario
                  format: email
      responses:
        201:
          description: "Usuario creado exitosamente"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  age:
                    type: integer
                  email:
                    type: string
